name = "gleam_mcp_todo"
version = "0.1.0"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_erlang = "~> 1.0"
gleam_http = "~> 4.0"
wisp = "~> 2.2"
mist = "~> 5.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
gleam_otp = "~> 1.2"
sqlight = "~> 1.0"
parrot = "~> 2.2"
envoy = ">= 1.1.0 and < 2.0.0"
simplifile = "~> 2.0"
dot_env = ">= 1.2.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
lustre = "~> 5.0"
glimit = { path = "lib/glimit" }

[dev-dependencies]
unitest = ">= 1.5.0 and < 2.0.0"
