//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import gleam/option.{type Option}
import parrot/dev

pub fn create_oauth_client(
  client_id client_id: String,
  client_secret_hash client_secret_hash: Option(String),
  client_secret_expires_at client_secret_expires_at: Int,
  redirect_uris redirect_uris: String,
  client_name client_name: String,
  token_endpoint_auth_method token_endpoint_auth_method: String,
  created_at created_at: Int,
) {
  let sql =
    "INSERT INTO oauth_clients (client_id, client_secret_hash, client_secret_expires_at, redirect_uris, client_name, token_endpoint_auth_method, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(client_id),
    dev.ParamNullable(
      option.map(client_secret_hash, fn(v) { dev.ParamString(v) }),
    ),
    dev.ParamInt(client_secret_expires_at),
    dev.ParamString(redirect_uris),
    dev.ParamString(client_name),
    dev.ParamString(token_endpoint_auth_method),
    dev.ParamInt(created_at),
  ])
}

pub type GetOauthClient {
  GetOauthClient(
    client_id: String,
    client_secret_hash: Option(String),
    client_secret_expires_at: Int,
    redirect_uris: String,
    client_name: String,
    token_endpoint_auth_method: String,
    created_at: Int,
  )
}

pub fn get_oauth_client(client_id client_id: String) {
  let sql =
    "SELECT client_id, client_secret_hash, client_secret_expires_at, redirect_uris, client_name, token_endpoint_auth_method, created_at
FROM oauth_clients WHERE client_id = ?"
  #(sql, [dev.ParamString(client_id)], get_oauth_client_decoder())
}

pub fn get_oauth_client_decoder() -> decode.Decoder(GetOauthClient) {
  use client_id <- decode.field(0, decode.string)
  use client_secret_hash <- decode.field(1, decode.optional(decode.string))
  use client_secret_expires_at <- decode.field(2, decode.int)
  use redirect_uris <- decode.field(3, decode.string)
  use client_name <- decode.field(4, decode.string)
  use token_endpoint_auth_method <- decode.field(5, decode.string)
  use created_at <- decode.field(6, decode.int)
  decode.success(GetOauthClient(
    client_id:,
    client_secret_hash:,
    client_secret_expires_at:,
    redirect_uris:,
    client_name:,
    token_endpoint_auth_method:,
    created_at:,
  ))
}

pub type GetUserById {
  GetUserById(id: Int, email: String, created_at: Int, updated_at: Int)
}

pub fn get_user_by_id(id id: Int) {
  let sql =
    "SELECT id, email, created_at, updated_at
FROM users WHERE id = ?"
  #(sql, [dev.ParamInt(id)], get_user_by_id_decoder())
}

pub fn get_user_by_id_decoder() -> decode.Decoder(GetUserById) {
  use id <- decode.field(0, decode.int)
  use email <- decode.field(1, decode.string)
  use created_at <- decode.field(2, decode.int)
  use updated_at <- decode.field(3, decode.int)
  decode.success(GetUserById(id:, email:, created_at:, updated_at:))
}

pub type CreateUser {
  CreateUser(id: Int, email: String, created_at: Int, updated_at: Int)
}

pub fn create_user(
  email email: String,
  created_at created_at: Int,
  updated_at updated_at: Int,
) {
  let sql =
    "INSERT INTO users (email, created_at, updated_at)
VALUES (?, ?, ?)
RETURNING id, email, created_at, updated_at"
  #(
    sql,
    [dev.ParamString(email), dev.ParamInt(created_at), dev.ParamInt(updated_at)],
    create_user_decoder(),
  )
}

pub fn create_user_decoder() -> decode.Decoder(CreateUser) {
  use id <- decode.field(0, decode.int)
  use email <- decode.field(1, decode.string)
  use created_at <- decode.field(2, decode.int)
  use updated_at <- decode.field(3, decode.int)
  decode.success(CreateUser(id:, email:, created_at:, updated_at:))
}

pub fn delete_old_users(created_at created_at: Int) {
  let sql = "DELETE FROM users WHERE created_at < ?"
  #(sql, [dev.ParamInt(created_at)])
}

pub fn create_mcp_session(
  session_id session_id: String,
  user_id user_id: Int,
  created_at created_at: Int,
  last_seen_at last_seen_at: Int,
) {
  let sql =
    "INSERT INTO mcp_sessions (session_id, user_id, created_at, last_seen_at)
VALUES (?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(session_id),
    dev.ParamInt(user_id),
    dev.ParamInt(created_at),
    dev.ParamInt(last_seen_at),
  ])
}

pub type GetMcpSession {
  GetMcpSession(
    session_id: String,
    user_id: Int,
    created_at: Int,
    last_seen_at: Int,
  )
}

pub fn get_mcp_session(session_id session_id: String) {
  let sql =
    "SELECT session_id, user_id, created_at, last_seen_at
FROM mcp_sessions WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)], get_mcp_session_decoder())
}

pub fn get_mcp_session_decoder() -> decode.Decoder(GetMcpSession) {
  use session_id <- decode.field(0, decode.string)
  use user_id <- decode.field(1, decode.int)
  use created_at <- decode.field(2, decode.int)
  use last_seen_at <- decode.field(3, decode.int)
  decode.success(GetMcpSession(
    session_id:,
    user_id:,
    created_at:,
    last_seen_at:,
  ))
}

pub fn touch_mcp_session(
  last_seen_at last_seen_at: Int,
  session_id session_id: String,
) {
  let sql = "UPDATE mcp_sessions SET last_seen_at = ? WHERE session_id = ?"
  #(sql, [dev.ParamInt(last_seen_at), dev.ParamString(session_id)])
}

pub fn delete_mcp_session(session_id session_id: String) {
  let sql = "DELETE FROM mcp_sessions WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub fn delete_old_mcp_sessions(last_seen_at last_seen_at: Int) {
  let sql = "DELETE FROM mcp_sessions WHERE last_seen_at < ?"
  #(sql, [dev.ParamInt(last_seen_at)])
}

pub type ListTodosByUser {
  ListTodosByUser(
    id: Int,
    user_id: Int,
    title: String,
    completed: Int,
    created_at: Int,
    updated_at: Int,
  )
}

pub fn list_todos_by_user(user_id user_id: Int) {
  let sql =
    "SELECT id, user_id, title, completed, created_at, updated_at
FROM todos WHERE user_id = ? ORDER BY completed ASC, created_at DESC"
  #(sql, [dev.ParamInt(user_id)], list_todos_by_user_decoder())
}

pub fn list_todos_by_user_decoder() -> decode.Decoder(ListTodosByUser) {
  use id <- decode.field(0, decode.int)
  use user_id <- decode.field(1, decode.int)
  use title <- decode.field(2, decode.string)
  use completed <- decode.field(3, decode.int)
  use created_at <- decode.field(4, decode.int)
  use updated_at <- decode.field(5, decode.int)
  decode.success(ListTodosByUser(
    id:,
    user_id:,
    title:,
    completed:,
    created_at:,
    updated_at:,
  ))
}

pub type GetTodoById {
  GetTodoById(
    id: Int,
    user_id: Int,
    title: String,
    completed: Int,
    created_at: Int,
    updated_at: Int,
  )
}

pub fn get_todo_by_id(id id: Int, user_id user_id: Int) {
  let sql =
    "SELECT id, user_id, title, completed, created_at, updated_at
FROM todos WHERE id = ? AND user_id = ?"
  #(sql, [dev.ParamInt(id), dev.ParamInt(user_id)], get_todo_by_id_decoder())
}

pub fn get_todo_by_id_decoder() -> decode.Decoder(GetTodoById) {
  use id <- decode.field(0, decode.int)
  use user_id <- decode.field(1, decode.int)
  use title <- decode.field(2, decode.string)
  use completed <- decode.field(3, decode.int)
  use created_at <- decode.field(4, decode.int)
  use updated_at <- decode.field(5, decode.int)
  decode.success(GetTodoById(
    id:,
    user_id:,
    title:,
    completed:,
    created_at:,
    updated_at:,
  ))
}

pub type CreateTodo {
  CreateTodo(
    id: Int,
    user_id: Int,
    title: String,
    completed: Int,
    created_at: Int,
    updated_at: Int,
  )
}

pub fn create_todo(
  user_id user_id: Int,
  title title: String,
  created_at created_at: Int,
  updated_at updated_at: Int,
) {
  let sql =
    "INSERT INTO todos (user_id, title, completed, created_at, updated_at)
VALUES (?, ?, 0, ?, ?)
RETURNING id, user_id, title, completed, created_at, updated_at"
  #(
    sql,
    [
      dev.ParamInt(user_id),
      dev.ParamString(title),
      dev.ParamInt(created_at),
      dev.ParamInt(updated_at),
    ],
    create_todo_decoder(),
  )
}

pub fn create_todo_decoder() -> decode.Decoder(CreateTodo) {
  use id <- decode.field(0, decode.int)
  use user_id <- decode.field(1, decode.int)
  use title <- decode.field(2, decode.string)
  use completed <- decode.field(3, decode.int)
  use created_at <- decode.field(4, decode.int)
  use updated_at <- decode.field(5, decode.int)
  decode.success(CreateTodo(
    id:,
    user_id:,
    title:,
    completed:,
    created_at:,
    updated_at:,
  ))
}

pub type UpdateTodo {
  UpdateTodo(
    id: Int,
    user_id: Int,
    title: String,
    completed: Int,
    created_at: Int,
    updated_at: Int,
  )
}

pub fn update_todo(
  title title: String,
  updated_at updated_at: Int,
  id id: Int,
  user_id user_id: Int,
) {
  let sql =
    "UPDATE todos
SET title = ?, updated_at = ?
WHERE id = ? AND user_id = ?
RETURNING id, user_id, title, completed, created_at, updated_at"
  #(
    sql,
    [
      dev.ParamString(title),
      dev.ParamInt(updated_at),
      dev.ParamInt(id),
      dev.ParamInt(user_id),
    ],
    update_todo_decoder(),
  )
}

pub fn update_todo_decoder() -> decode.Decoder(UpdateTodo) {
  use id <- decode.field(0, decode.int)
  use user_id <- decode.field(1, decode.int)
  use title <- decode.field(2, decode.string)
  use completed <- decode.field(3, decode.int)
  use created_at <- decode.field(4, decode.int)
  use updated_at <- decode.field(5, decode.int)
  decode.success(UpdateTodo(
    id:,
    user_id:,
    title:,
    completed:,
    created_at:,
    updated_at:,
  ))
}

pub type CompleteTodo {
  CompleteTodo(
    id: Int,
    user_id: Int,
    title: String,
    completed: Int,
    created_at: Int,
    updated_at: Int,
  )
}

pub fn complete_todo(
  updated_at updated_at: Int,
  id id: Int,
  user_id user_id: Int,
) {
  let sql =
    "UPDATE todos
SET completed = CASE WHEN completed = 0 THEN 1 ELSE 0 END, updated_at = ?
WHERE id = ? AND user_id = ?
RETURNING id, user_id, title, completed, created_at, updated_at"
  #(
    sql,
    [dev.ParamInt(updated_at), dev.ParamInt(id), dev.ParamInt(user_id)],
    complete_todo_decoder(),
  )
}

pub fn complete_todo_decoder() -> decode.Decoder(CompleteTodo) {
  use id <- decode.field(0, decode.int)
  use user_id <- decode.field(1, decode.int)
  use title <- decode.field(2, decode.string)
  use completed <- decode.field(3, decode.int)
  use created_at <- decode.field(4, decode.int)
  use updated_at <- decode.field(5, decode.int)
  decode.success(CompleteTodo(
    id:,
    user_id:,
    title:,
    completed:,
    created_at:,
    updated_at:,
  ))
}

pub type DeleteTodo {
  DeleteTodo(
    id: Int,
    user_id: Int,
    title: String,
    completed: Int,
    created_at: Int,
    updated_at: Int,
  )
}

pub fn delete_todo(id id: Int, user_id user_id: Int) {
  let sql =
    "DELETE FROM todos WHERE id = (
  SELECT t.id FROM todos t WHERE t.id = ? AND t.user_id = ? LIMIT 1
)
RETURNING id, user_id, title, completed, created_at, updated_at"
  #(sql, [dev.ParamInt(id), dev.ParamInt(user_id)], delete_todo_decoder())
}

pub fn delete_todo_decoder() -> decode.Decoder(DeleteTodo) {
  use id <- decode.field(0, decode.int)
  use user_id <- decode.field(1, decode.int)
  use title <- decode.field(2, decode.string)
  use completed <- decode.field(3, decode.int)
  use created_at <- decode.field(4, decode.int)
  use updated_at <- decode.field(5, decode.int)
  decode.success(DeleteTodo(
    id:,
    user_id:,
    title:,
    completed:,
    created_at:,
    updated_at:,
  ))
}

pub fn delete_todos_for_old_users(created_at created_at: Int) {
  let sql =
    "DELETE FROM todos WHERE user_id IN (
  SELECT u.id FROM users u WHERE u.created_at < ?
)"
  #(sql, [dev.ParamInt(created_at)])
}

pub fn create_refresh_token(
  token_hash token_hash: String,
  client_id client_id: String,
  user_id user_id: Int,
  resource resource: String,
  scope scope: String,
  expires_at expires_at: Int,
  created_at created_at: Int,
) {
  let sql =
    "INSERT INTO oauth_refresh_tokens (token_hash, client_id, user_id, resource, scope, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(token_hash),
    dev.ParamString(client_id),
    dev.ParamInt(user_id),
    dev.ParamString(resource),
    dev.ParamString(scope),
    dev.ParamInt(expires_at),
    dev.ParamInt(created_at),
  ])
}

pub type GetRefreshToken {
  GetRefreshToken(
    token_hash: String,
    client_id: String,
    user_id: Int,
    resource: String,
    scope: String,
    expires_at: Int,
    revoked_at: Option(Int),
    created_at: Int,
  )
}

pub fn get_refresh_token(token_hash token_hash: String) {
  let sql =
    "SELECT token_hash, client_id, user_id, resource, scope, expires_at, revoked_at, created_at
FROM oauth_refresh_tokens WHERE token_hash = ?"
  #(sql, [dev.ParamString(token_hash)], get_refresh_token_decoder())
}

pub fn get_refresh_token_decoder() -> decode.Decoder(GetRefreshToken) {
  use token_hash <- decode.field(0, decode.string)
  use client_id <- decode.field(1, decode.string)
  use user_id <- decode.field(2, decode.int)
  use resource <- decode.field(3, decode.string)
  use scope <- decode.field(4, decode.string)
  use expires_at <- decode.field(5, decode.int)
  use revoked_at <- decode.field(6, decode.optional(decode.int))
  use created_at <- decode.field(7, decode.int)
  decode.success(GetRefreshToken(
    token_hash:,
    client_id:,
    user_id:,
    resource:,
    scope:,
    expires_at:,
    revoked_at:,
    created_at:,
  ))
}

pub fn revoke_refresh_token(
  revoked_at revoked_at: Option(Int),
  token_hash token_hash: String,
) {
  let sql =
    "UPDATE oauth_refresh_tokens SET revoked_at = ? WHERE token_hash = ?"
  #(sql, [
    dev.ParamNullable(option.map(revoked_at, fn(v) { dev.ParamInt(v) })),
    dev.ParamString(token_hash),
  ])
}

pub fn delete_expired_refresh_tokens(expires_at expires_at: Int) {
  let sql = "DELETE FROM oauth_refresh_tokens WHERE expires_at < ?"
  #(sql, [dev.ParamInt(expires_at)])
}

pub fn create_authorization_code(
  code code: String,
  client_id client_id: String,
  user_id user_id: Int,
  redirect_uri redirect_uri: String,
  code_challenge code_challenge: String,
  resource resource: String,
  scope scope: String,
  expires_at expires_at: Int,
  created_at created_at: Int,
) {
  let sql =
    "INSERT INTO oauth_authorization_codes (code, client_id, user_id, redirect_uri, code_challenge, resource, scope, expires_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(code),
    dev.ParamString(client_id),
    dev.ParamInt(user_id),
    dev.ParamString(redirect_uri),
    dev.ParamString(code_challenge),
    dev.ParamString(resource),
    dev.ParamString(scope),
    dev.ParamInt(expires_at),
    dev.ParamInt(created_at),
  ])
}

pub type GetAuthorizationCode {
  GetAuthorizationCode(
    code: String,
    client_id: String,
    user_id: Int,
    redirect_uri: String,
    code_challenge: String,
    resource: String,
    scope: String,
    expires_at: Int,
    created_at: Int,
  )
}

pub fn get_authorization_code(code code: String) {
  let sql =
    "SELECT code, client_id, user_id, redirect_uri, code_challenge, resource, scope, expires_at, created_at
FROM oauth_authorization_codes WHERE code = ?"
  #(sql, [dev.ParamString(code)], get_authorization_code_decoder())
}

pub fn get_authorization_code_decoder() -> decode.Decoder(GetAuthorizationCode) {
  use code <- decode.field(0, decode.string)
  use client_id <- decode.field(1, decode.string)
  use user_id <- decode.field(2, decode.int)
  use redirect_uri <- decode.field(3, decode.string)
  use code_challenge <- decode.field(4, decode.string)
  use resource <- decode.field(5, decode.string)
  use scope <- decode.field(6, decode.string)
  use expires_at <- decode.field(7, decode.int)
  use created_at <- decode.field(8, decode.int)
  decode.success(GetAuthorizationCode(
    code:,
    client_id:,
    user_id:,
    redirect_uri:,
    code_challenge:,
    resource:,
    scope:,
    expires_at:,
    created_at:,
  ))
}

pub fn delete_authorization_code(code code: String) {
  let sql = "DELETE FROM oauth_authorization_codes WHERE code = ?"
  #(sql, [dev.ParamString(code)])
}

pub fn delete_expired_codes(expires_at expires_at: Int) {
  let sql = "DELETE FROM oauth_authorization_codes WHERE expires_at < ?"
  #(sql, [dev.ParamInt(expires_at)])
}

pub type GetUserEmailByEmail {
  GetUserEmailByEmail(
    id: Int,
    email: String,
    user_id: Option(Int),
    token_hash: Option(String),
    token_expires_at: Option(Int),
    previous_token_hash: Option(String),
    verified_at: Option(Int),
    created_at: Int,
  )
}

pub fn get_user_email_by_email(email email: String) {
  let sql =
    "SELECT id, email, user_id, token_hash, token_expires_at,
       previous_token_hash, verified_at, created_at
FROM user_emails WHERE email = ?"
  #(sql, [dev.ParamString(email)], get_user_email_by_email_decoder())
}

pub fn get_user_email_by_email_decoder() -> decode.Decoder(GetUserEmailByEmail) {
  use id <- decode.field(0, decode.int)
  use email <- decode.field(1, decode.string)
  use user_id <- decode.field(2, decode.optional(decode.int))
  use token_hash <- decode.field(3, decode.optional(decode.string))
  use token_expires_at <- decode.field(4, decode.optional(decode.int))
  use previous_token_hash <- decode.field(5, decode.optional(decode.string))
  use verified_at <- decode.field(6, decode.optional(decode.int))
  use created_at <- decode.field(7, decode.int)
  decode.success(GetUserEmailByEmail(
    id:,
    email:,
    user_id:,
    token_hash:,
    token_expires_at:,
    previous_token_hash:,
    verified_at:,
    created_at:,
  ))
}

pub type CreateUserEmail {
  CreateUserEmail(
    id: Int,
    email: String,
    user_id: Option(Int),
    token_hash: Option(String),
    token_expires_at: Option(Int),
    previous_token_hash: Option(String),
    verified_at: Option(Int),
    created_at: Int,
  )
}

pub fn create_user_email(email email: String, created_at created_at: Int) {
  let sql =
    "INSERT INTO user_emails (email, created_at)
VALUES (?, ?)
RETURNING id, email, user_id, token_hash, token_expires_at,
          previous_token_hash, verified_at, created_at"
  #(
    sql,
    [dev.ParamString(email), dev.ParamInt(created_at)],
    create_user_email_decoder(),
  )
}

pub fn create_user_email_decoder() -> decode.Decoder(CreateUserEmail) {
  use id <- decode.field(0, decode.int)
  use email <- decode.field(1, decode.string)
  use user_id <- decode.field(2, decode.optional(decode.int))
  use token_hash <- decode.field(3, decode.optional(decode.string))
  use token_expires_at <- decode.field(4, decode.optional(decode.int))
  use previous_token_hash <- decode.field(5, decode.optional(decode.string))
  use verified_at <- decode.field(6, decode.optional(decode.int))
  use created_at <- decode.field(7, decode.int)
  decode.success(CreateUserEmail(
    id:,
    email:,
    user_id:,
    token_hash:,
    token_expires_at:,
    previous_token_hash:,
    verified_at:,
    created_at:,
  ))
}

pub fn set_verification_token(
  token_hash token_hash: Option(String),
  token_expires_at token_expires_at: Option(Int),
  email email: String,
) {
  let sql =
    "UPDATE user_emails
SET token_hash = ?, token_expires_at = ?, previous_token_hash = token_hash
WHERE email = ?"
  #(sql, [
    dev.ParamNullable(option.map(token_hash, fn(v) { dev.ParamString(v) })),
    dev.ParamNullable(option.map(token_expires_at, fn(v) { dev.ParamInt(v) })),
    dev.ParamString(email),
  ])
}

pub fn verify_user_email(
  verified_at verified_at: Option(Int),
  email email: String,
) {
  let sql =
    "UPDATE user_emails
SET verified_at = ?, token_hash = NULL, token_expires_at = NULL, previous_token_hash = NULL
WHERE email = ?"
  #(sql, [
    dev.ParamNullable(option.map(verified_at, fn(v) { dev.ParamInt(v) })),
    dev.ParamString(email),
  ])
}

pub fn claim_user_email(user_id user_id: Option(Int), email email: String) {
  let sql =
    "UPDATE user_emails
SET user_id = ?
WHERE email = ? AND user_id IS NULL"
  #(sql, [
    dev.ParamNullable(option.map(user_id, fn(v) { dev.ParamInt(v) })),
    dev.ParamString(email),
  ])
}

pub fn delete_user_emails_for_old_users(created_at created_at: Int) {
  let sql =
    "DELETE FROM user_emails WHERE user_id IN (
  SELECT u.id FROM users u WHERE u.created_at < ?
)"
  #(sql, [dev.ParamInt(created_at)])
}
